# Generated by Django 5.2.16 on 2026-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
