# Generated by Django 5.2.16 on 2026-07-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vendor', 'Vendor'), ('school', 'School'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('other', 'Other')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('owed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('last_purchase', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
